### PR TITLE
#17 Angular simple site

### PR DESCRIPTION
**Pull request by olinator98**
This is the newest version of the AngularJS example.

### CODE REVIEW

**Comment by Christian-Seematter** [comment]
Don't you think this is a bit overkill? All that's needed really is the result from `ng new TabSolution-Client` to generate a basic, barebone angular application. There are [great tutorials](https://spring.io/guides/gs/consuming-rest-angularjs/) on how to create and extend this with http requests to use the restAPI.

**Comment by bregySilvan** [comment]
@olinator98 
According to the issue title, this should be a *simple* example. This should be a mini project with the absolute minimum to run an angular 2 application. When having the basic app it's a nice example to start for others to lookup start commands and basic settings.

Pls revert your changes and set up a small example like in here> https://angular.io/guide/quickstart
Contact me when support is needed.

**Comment by olinator98** [comment]
@Christian-Seematter 
Thanks for the feedback. 
Of course, there's a lot of stuff in this example and it isn't as simple as possible. I have to say that I've created this just for testing and learning some basics of AngularJS. It isn't relevant for our main-project. But now, I've got a basic knowledge and I'm able to start with the implemention of the RestAPI. Thanks for the link, I'll have a look at it. 

@bregySilvan 
There's already a basic project with AngularJS in our repository. Just have a look at the branch "angular" created by @TheScorpio13 . I think that's what's you mean. 

Cherio

**Comment by bregySilvan** [comment]
@olinator98 
Yes, I thought this was the example program. But still, I think your code is way too large for being a "simple Angular site". You now learned your stuff and my question is,  why do we have this issue?

**Comment by Christian-Seematter** [comment]
@olinator98 Close this PR at your leisure if this demo is no longer required.

**Pull request closed without merging**
